### ISSUE TITLE
osx safair bug

### ISSUE THREAD

**Issue by sunsan05** [dvlden/Vidage#14]
Unhandled Promise Rejection: NotAllowedError (DOM Exception 35): The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission
![1](https://user-images.githubusercontent.com/14139451/34758202-041e5c72-f611-11e7-9dc0-bb72bf36161f.png)

**Comment by dvlden** [comment]
Hello @sunsan05 and thank you for taking a look at Vidage.

Can you please tell me how did you produce such error because Vidage itself does not use Promises. I wasn't sure if it's an dependency, but I just checked it out and it does not seem that two small dependencies are using promises either.

I tried fresh install and I couldn't see such error in Safari v11.0.2

**Comment by sunsan05** [comment]
OS：macOS High Sierra v10.13.2 (17C205) 
Safari：11.0.2 (13604.4.7.1.6)
URL：https://dvlden.github.io/Vidage/

play() Function error

**Comment by dvlden** [comment]
We're on same system, using same browser.
Somehow, it simply works for me?
https://d.pr/i/uzptO5

**Comment by dvlden** [comment]
I'll assume that you figured your problem and resolved it.
