### ISSUE TITLE
Remove video if it is mobile device

### ISSUE THREAD

**Issue by lgg** [dvLden/Vidage#6]
For now Vidage just use `display: none`, but maybe remove `<video>` element from page?
Of course make this optional.

### Why i'm asking for this?
I'm trying to use Vidage with https://github.com/alvarotrigo/fullPage.js and on desktops i need video to be autoplayed, but on mobile devices i need image instead. But fullPage.js starts video on mobiles.

### Wait, what? It's seem like a trouble with  fullPage.js not with Vidage
Yeap and nope. As i understand, Vidage's task is to define what to show: image or video, so i'm asking about this here

What do you think about this?

**Comment by dvLden** [comment]
_**Vidage in short:**_
• No touch – Fallback image is shown, then it waits until video is loaded enough to be played and plays it. There's also a resize check so it will pause the video on smaller screens and unpause again when width is large enough. 

• Touch – Pauses video on every touch device and show image instead.

As you stated, you want Vidage to remove `<video />` element and sources completely. You did not check the `init()` method tho. It would need to also re-add that removed element and sources when necessery, because it's not only checking for touch device, but also the `max-width: 34em`. 

So your commit would remove `<video />` also on those small browser sizes for desktop, but when they resize it back to larger width, it would throw errors.

I'll think about it and let you know what I decide and manage to do. Perhaps it can be an separate extension for such a purpose / combination.

**Comment by lgg** [comment]
@dvLden hmm, i think when developer set `deleteVideo` to true it's okay not to show video on bigger screens.

But in the other hand it is really worth to think. I'll try to change my PR to fit your requirements.

**Comment by dvLden** [comment]
Implemented in version `0.2.0`. Hope it works out for you in combination with that plugin, let me know.

**Comment by lgg** [comment]
@dvLden unfortunately it doesn't work for me ;(

if i write: `new Vidage('#video', true);`

On mobile it still play video.
On desktop it removes video.

**Comment by lgg** [comment]
@dvLden you can check my project and this situation here: https://github.com/mireadev/landing-sumirea/tree/vidage0.2test

`npm install && gulp`
it will run browserSync on your localhost and you can connect to it with your mobile phone

i tested on iphone 5s with safari+chrome, ios8.1

**Comment by dvLden** [comment]
new Vidage(selector, helperClass = 'Vidage--allow', removeVideo = false);

I am really unsure if in JS we can do:
`new Vidage('#video', removeVideo = true);`

Or we must pass all params...
`new Vidage('#video', 'Vidage--allow', true);`

Let me know what works out of these two. Because if we can't pass it like in first example, then I'd better make object for options.

**Comment by lgg** [comment]
@dvLden unfortunately it doesn't work ;(

Test yourself: https://mireadev.github.io/landing-sumirea/

**Comment by dvLden** [comment]
Pretty sure it worked, but seem like I missed something.

`Uncaught ReferenceError: removeVideo is not defined`

I'll look into it

**Comment by dvLden** [comment]
Looks like it's a conflict between `removeVideo function` and `removeVideo = false` argument. 
I changed the name of that and now it works, but I will not push to git and npm yet.

**Comment by lgg** [comment]
@dvLden if you can, please push it to /dev/ branch or something and i will test it.

**Comment by dvLden** [comment]
@lgg  **0.2.5 is out!**

I resolved this and some other issues along. 

In your case specifically, now you should do following:
```javascript
new Vidage('#video', {
    videoRemoval: true
});
```

**Comment by alanhamlett** [comment]
So what does `videoRemoval` option actually do? When `true` it removes the `video` elements from DOM on Mobile?

Edit: Tested and yes it causes `video` element to be removed from DOM instead of `display:none`, but only on Mobile. Why not make the default `true`?
